# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.conflict_error import ConflictError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_code_resp import GithubComMktAgiAixInternalPkgGinxCodeResp
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_payments_internal_web_wallet_v2response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_payments_internal_web_wallet_transfer_envelope import (
    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_payments_internal_web_wallet_transfer_v2response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_payments_internal_web_wallet_v2response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response,
)
from .types.post_api_v1payment_wallets_id_convert_currency_request_body import (
    PostApiV1PaymentWalletsIdConvertCurrencyRequestBody,
)
from .types.post_api_v1payment_wallets_id_transfer_request_body import PostApiV1PaymentWalletsIdTransferRequestBody
from .types.post_api_v1payment_wallets_id_transfer_to_main_request_body import (
    PostApiV1PaymentWalletsIdTransferToMainRequestBody,
)
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWalletsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_transfer_detail(
        self, transfer_no: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response]:
        """
        Get the details of a wallet transfer by transfer number.

        Parameters
        ----------
        transfer_no : int
            Transfer number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallet/transfers/{jsonable_encoder(transfer_no)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_wallets(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response]:
        """
        List all wallets for the current authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/payment/wallets",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_wallet(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response]:
        """
        Get a single wallet by ID with ownership verification.

        Parameters
        ----------
        id : int
            Wallet ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def convert_wallet_currency(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdConvertCurrencyRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Convert all balance from the source wallet to a target-currency wallet in-place, applying the exchange rate with markup. Idempotent via idempotency_key.

        Parameters
        ----------
        id : int
            Source wallet ID

        request : PostApiV1PaymentWalletsIdConvertCurrencyRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/convert-currency",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdConvertCurrencyRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_wallet_transactions(
        self,
        id: int,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        List paginated transactions for a specific wallet.

        Parameters
        ----------
        id : int
            Wallet ID

        page : typing.Optional[int]
            Page number (default 1)

        limit : typing.Optional[int]
            Items per page (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transactions",
            method="GET",
            params={
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def transfer_between_wallets(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdTransferRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]:
        """
        Transfer funds from the source wallet to another wallet belonging to the same user.

        Parameters
        ----------
        id : int
            Source wallet ID

        request : PostApiV1PaymentWalletsIdTransferRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transfer",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdTransferRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def transfer_revenue_wallet_balance_to_main_wallet(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdTransferToMainRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]:
        """
        Transfer all balance from a revenue wallet to the user's main wallet. Only revenue wallets are eligible.

        Parameters
        ----------
        id : int
            Revenue wallet ID

        request : PostApiV1PaymentWalletsIdTransferToMainRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transfer-to-main",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdTransferToMainRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWalletsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_transfer_detail(
        self, transfer_no: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response]:
        """
        Get the details of a wallet transfer by transfer number.

        Parameters
        ----------
        transfer_no : int
            Transfer number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallet/transfers/{jsonable_encoder(transfer_no)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_wallets(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response]:
        """
        List all wallets for the current authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/payment/wallets",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayInternalPaymentsInternalWebWalletV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_wallet(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response]:
        """
        Get a single wallet by ID with ownership verification.

        Parameters
        ----------
        id : int
            Wallet ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def convert_wallet_currency(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdConvertCurrencyRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Convert all balance from the source wallet to a target-currency wallet in-place, applying the exchange rate with markup. Idempotent via idempotency_key.

        Parameters
        ----------
        id : int
            Source wallet ID

        request : PostApiV1PaymentWalletsIdConvertCurrencyRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/convert-currency",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdConvertCurrencyRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_wallet_transactions(
        self,
        id: int,
        *,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        List paginated transactions for a specific wallet.

        Parameters
        ----------
        id : int
            Wallet ID

        page : typing.Optional[int]
            Page number (default 1)

        limit : typing.Optional[int]
            Items per page (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transactions",
            method="GET",
            params={
                "page": page,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def transfer_between_wallets(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdTransferRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]:
        """
        Transfer funds from the source wallet to another wallet belonging to the same user.

        Parameters
        ----------
        id : int
            Source wallet ID

        request : PostApiV1PaymentWalletsIdTransferRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transfer",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdTransferRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def transfer_revenue_wallet_balance_to_main_wallet(
        self,
        id: int,
        *,
        request: PostApiV1PaymentWalletsIdTransferToMainRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]:
        """
        Transfer all balance from a revenue wallet to the user's main wallet. Only revenue wallets are eligible.

        Parameters
        ----------
        id : int
            Revenue wallet ID

        request : PostApiV1PaymentWalletsIdTransferToMainRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/payment/wallets/{jsonable_encoder(id)}/transfer-to-main",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostApiV1PaymentWalletsIdTransferToMainRequestBody, direction="write"
            ),
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalPaymentsInternalWebWalletTransferEnvelope,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
