# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_messaging_internal_web_send_message_req import InternalMessagingInternalWebSendMessageReq

PostMessagingConversationsConvIdMessagesRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalMessagingInternalWebSendMessageReq
]
