# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_aigateway_internal_web_test_provider_request import (
    InternalAigatewayInternalWebTestProviderRequest,
)

PostGatewayUserIdProvidersTestRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalAigatewayInternalWebTestProviderRequest
]
