# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_accounts_internal_web_upsert_secret_req import InternalAccountsInternalWebUpsertSecretReq

PutSecretsUserIdKeyRequestBody = typing.Union[typing.Dict[str, typing.Any], InternalAccountsInternalWebUpsertSecretReq]
