# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_aigateway_internal_web_top_resources_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTopResourcesResponse,
)
from .raw_client import AsyncRawAdminMarketplaceClient, RawAdminMarketplaceClient


class AdminMarketplaceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAdminMarketplaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAdminMarketplaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAdminMarketplaceClient
        """
        return self._raw_client

    def top_resources_ranking_admin(
        self,
        *,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTopResourcesResponse:
        """
        Returns top models ranked by call count or revenue. Only includes listed/published models.

        Parameters
        ----------
        sort : typing.Optional[str]
            Sort field: calls (default) or revenue

        limit : typing.Optional[int]
            Max results (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTopResourcesResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.admin_marketplace.top_resources_ranking_admin()
        """
        _response = self._raw_client.top_resources_ranking_admin(
            sort=sort, limit=limit, request_options=request_options
        )
        return _response.data


class AsyncAdminMarketplaceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAdminMarketplaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAdminMarketplaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAdminMarketplaceClient
        """
        return self._raw_client

    async def top_resources_ranking_admin(
        self,
        *,
        sort: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTopResourcesResponse:
        """
        Returns top models ranked by call count or revenue. Only includes listed/published models.

        Parameters
        ----------
        sort : typing.Optional[str]
            Sort field: calls (default) or revenue

        limit : typing.Optional[int]
            Max results (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebTopResourcesResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.admin_marketplace.top_resources_ranking_admin()


        asyncio.run(main())
        """
        _response = await self._raw_client.top_resources_ranking_admin(
            sort=sort, limit=limit, request_options=request_options
        )
        return _response.data
