# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_messaging_internal_web_add_participant_req import InternalMessagingInternalWebAddParticipantReq

PostMessagingConversationsConvIdParticipantsRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalMessagingInternalWebAddParticipantReq
]
