# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .post_auth_email_send_request import PostAuthEmailSendRequest
    from .post_auth_email_verify_request import PostAuthEmailVerifyRequest
    from .post_auth_github_request import PostAuthGithubRequest
    from .post_auth_google_request import PostAuthGoogleRequest
    from .post_auth_sms_send_request import PostAuthSmsSendRequest
    from .post_auth_sms_verify_request import PostAuthSmsVerifyRequest
_dynamic_imports: typing.Dict[str, str] = {
    "PostAuthEmailSendRequest": ".post_auth_email_send_request",
    "PostAuthEmailVerifyRequest": ".post_auth_email_verify_request",
    "PostAuthGithubRequest": ".post_auth_github_request",
    "PostAuthGoogleRequest": ".post_auth_google_request",
    "PostAuthSmsSendRequest": ".post_auth_sms_send_request",
    "PostAuthSmsVerifyRequest": ".post_auth_sms_verify_request",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PostAuthEmailSendRequest",
    "PostAuthEmailVerifyRequest",
    "PostAuthGithubRequest",
    "PostAuthGoogleRequest",
    "PostAuthSmsSendRequest",
    "PostAuthSmsVerifyRequest",
]
