# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_anthropic_message_response import (
    GithubComMktAgiAixInternalPkgGinxResultAnthropicMessageResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_any import GithubComMktAgiAixInternalPkgGinxResultAny
from .raw_client import AsyncRawChatClient, RawChatClient
from .types.post_messages_request import PostMessagesRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ChatClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawChatClient
        """
        return self._raw_client

    def send_a_chat_completion_request(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Proxies a chat completion to the upstream LLM provider. Supports streaming (SSE) and non-streaming.

        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.chat.send_a_chat_completion_request(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_a_chat_completion_request(request=request, request_options=request_options)
        return _response.data

    def send_an_anthropic_compatible_message_request(
        self, *, request: PostMessagesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAnthropicMessageResponse:
        """
        Adapts Anthropic Messages API requests and responses to the existing AI gateway routing and proxy pipeline.

        Parameters
        ----------
        request : PostMessagesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAnthropicMessageResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.chat.send_an_anthropic_compatible_message_request(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_an_anthropic_compatible_message_request(
            request=request, request_options=request_options
        )
        return _response.data

    def list_available_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Returns all enabled models with extended metadata (name, description, capabilities, default flag).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.chat.list_available_models()
        """
        _response = self._raw_client.list_available_models(request_options=request_options)
        return _response.data

    def send_a_responses_api_request(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Adapts OpenAI Responses API requests to Chat Completions. Primarily for Codex CLI compatibility.

        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.chat.send_a_responses_api_request(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_a_responses_api_request(request=request, request_options=request_options)
        return _response.data


class AsyncChatClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawChatClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawChatClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawChatClient
        """
        return self._raw_client

    async def send_a_chat_completion_request(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Proxies a chat completion to the upstream LLM provider. Supports streaming (SSE) and non-streaming.

        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.send_a_chat_completion_request(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_a_chat_completion_request(
            request=request, request_options=request_options
        )
        return _response.data

    async def send_an_anthropic_compatible_message_request(
        self, *, request: PostMessagesRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAnthropicMessageResponse:
        """
        Adapts Anthropic Messages API requests and responses to the existing AI gateway routing and proxy pipeline.

        Parameters
        ----------
        request : PostMessagesRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAnthropicMessageResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.send_an_anthropic_compatible_message_request(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_an_anthropic_compatible_message_request(
            request=request, request_options=request_options
        )
        return _response.data

    async def list_available_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Returns all enabled models with extended metadata (name, description, capabilities, default flag).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.list_available_models()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_available_models(request_options=request_options)
        return _response.data

    async def send_a_responses_api_request(
        self, *, request: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Adapts OpenAI Responses API requests to Chat Completions. Primarily for Codex CLI compatibility.

        Parameters
        ----------
        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.chat.send_a_responses_api_request(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_a_responses_api_request(
            request=request, request_options=request_options
        )
        return _response.data
