# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_accounts_internal_web_auth_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_accounts_internal_web_captcha_generate_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse,
)
from .raw_client import AsyncRawAuthClient, RawAuthClient
from .types.post_auth_email_send_request import PostAuthEmailSendRequest
from .types.post_auth_email_verify_request import PostAuthEmailVerifyRequest
from .types.post_auth_github_request import PostAuthGithubRequest
from .types.post_auth_google_request import PostAuthGoogleRequest
from .types.post_auth_sms_send_request import PostAuthSmsSendRequest
from .types.post_auth_sms_verify_request import PostAuthSmsVerifyRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AuthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAuthClient
        """
        return self._raw_client

    def generate_image_captcha(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse:
        """
        Generate a CAPTCHA image and return the token plus base64-encoded PNG.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.generate_image_captcha()
        """
        _response = self._raw_client.generate_image_captcha(request_options=request_options)
        return _response.data

    def send_email_verification_code(
        self, *, request: PostAuthEmailSendRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Send a one-time verification code to the given email address. Rate-limited to 1 per 60 seconds.

        Parameters
        ----------
        request : PostAuthEmailSendRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.send_email_verification_code(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_email_verification_code(request=request, request_options=request_options)
        return _response.data

    def verify_email_code_and_authenticate(
        self, *, request: PostAuthEmailVerifyRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse:
        """
        Verify the email code and return JWT tokens. Creates a new user account if this email is not registered.

        Parameters
        ----------
        request : PostAuthEmailVerifyRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse
            tokens set via Set-Cookie

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.verify_email_code_and_authenticate(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.verify_email_code_and_authenticate(
            request=request, request_options=request_options
        )
        return _response.data

    def exchange_git_hub_code_for_tokens_api(
        self, *, request: PostAuthGithubRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Exchange a GitHub OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.

        Parameters
        ----------
        request : PostAuthGithubRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.exchange_git_hub_code_for_tokens_api(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.exchange_git_hub_code_for_tokens_api(
            request=request, request_options=request_options
        )
        return _response.data

    def git_hub_o_auth_callback_web(
        self, *, state: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Handle the GitHub OAuth redirect, exchange the code for tokens, and redirect to the frontend.

        Parameters
        ----------
        state : str
            OAuth state

        code : str
            GitHub authorization code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.git_hub_o_auth_callback_web(
            state="state",
            code="code",
        )
        """
        _response = self._raw_client.git_hub_o_auth_callback_web(
            state=state, code=code, request_options=request_options
        )
        return _response.data

    def initiate_git_hub_o_auth(self, *, ref_uri: str, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Generate an OAuth state and redirect the browser to GitHub's authorization page.

        Parameters
        ----------
        ref_uri : str
            Post-auth redirect URI (will be redirected to verbatim)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.initiate_git_hub_o_auth(
            ref_uri="ref_uri",
        )
        """
        _response = self._raw_client.initiate_git_hub_o_auth(ref_uri=ref_uri, request_options=request_options)
        return _response.data

    def exchange_google_code_for_tokens_api(
        self, *, request: PostAuthGoogleRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Exchange a Google OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.

        Parameters
        ----------
        request : PostAuthGoogleRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.exchange_google_code_for_tokens_api(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.exchange_google_code_for_tokens_api(
            request=request, request_options=request_options
        )
        return _response.data

    def google_o_auth_callback_web(
        self, *, state: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Handle the Google OAuth redirect, exchange the code for tokens, and redirect to the frontend.

        Parameters
        ----------
        state : str
            OAuth state

        code : str
            Google authorization code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.google_o_auth_callback_web(
            state="state",
            code="code",
        )
        """
        _response = self._raw_client.google_o_auth_callback_web(state=state, code=code, request_options=request_options)
        return _response.data

    def initiate_google_o_auth(self, *, ref_uri: str, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Generate an OAuth state and redirect the browser to Google's authorization page.

        Parameters
        ----------
        ref_uri : str
            Post-auth redirect URI (will be redirected to verbatim)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.initiate_google_o_auth(
            ref_uri="ref_uri",
        )
        """
        _response = self._raw_client.initiate_google_o_auth(ref_uri=ref_uri, request_options=request_options)
        return _response.data

    def logout_current_user(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Invalidate all sessions for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.logout_current_user()
        """
        _response = self._raw_client.logout_current_user(request_options=request_options)
        return _response.data

    def send_sms_verification_code(
        self, *, request: PostAuthSmsSendRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Send a one-time verification code to the given phone number. Rate-limited to 1 per 60 seconds.

        Parameters
        ----------
        request : PostAuthSmsSendRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.send_sms_verification_code(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_sms_verification_code(request=request, request_options=request_options)
        return _response.data

    def verify_sms_code_and_authenticate(
        self, *, request: PostAuthSmsVerifyRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse:
        """
        Verify the SMS code and return JWT tokens. Creates a new user account if this phone is not registered.

        Parameters
        ----------
        request : PostAuthSmsVerifyRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse
            tokens set via Set-Cookie

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.auth.verify_sms_code_and_authenticate(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.verify_sms_code_and_authenticate(request=request, request_options=request_options)
        return _response.data


class AsyncAuthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAuthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAuthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAuthClient
        """
        return self._raw_client

    async def generate_image_captcha(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse:
        """
        Generate a CAPTCHA image and return the token plus base64-encoded PNG.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebCaptchaGenerateResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.generate_image_captcha()


        asyncio.run(main())
        """
        _response = await self._raw_client.generate_image_captcha(request_options=request_options)
        return _response.data

    async def send_email_verification_code(
        self, *, request: PostAuthEmailSendRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Send a one-time verification code to the given email address. Rate-limited to 1 per 60 seconds.

        Parameters
        ----------
        request : PostAuthEmailSendRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.send_email_verification_code(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_email_verification_code(
            request=request, request_options=request_options
        )
        return _response.data

    async def verify_email_code_and_authenticate(
        self, *, request: PostAuthEmailVerifyRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse:
        """
        Verify the email code and return JWT tokens. Creates a new user account if this email is not registered.

        Parameters
        ----------
        request : PostAuthEmailVerifyRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse
            tokens set via Set-Cookie

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.verify_email_code_and_authenticate(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_email_code_and_authenticate(
            request=request, request_options=request_options
        )
        return _response.data

    async def exchange_git_hub_code_for_tokens_api(
        self, *, request: PostAuthGithubRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Exchange a GitHub OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.

        Parameters
        ----------
        request : PostAuthGithubRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.exchange_git_hub_code_for_tokens_api(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.exchange_git_hub_code_for_tokens_api(
            request=request, request_options=request_options
        )
        return _response.data

    async def git_hub_o_auth_callback_web(
        self, *, state: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Handle the GitHub OAuth redirect, exchange the code for tokens, and redirect to the frontend.

        Parameters
        ----------
        state : str
            OAuth state

        code : str
            GitHub authorization code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.git_hub_o_auth_callback_web(
                state="state",
                code="code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.git_hub_o_auth_callback_web(
            state=state, code=code, request_options=request_options
        )
        return _response.data

    async def initiate_git_hub_o_auth(
        self, *, ref_uri: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Generate an OAuth state and redirect the browser to GitHub's authorization page.

        Parameters
        ----------
        ref_uri : str
            Post-auth redirect URI (will be redirected to verbatim)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.initiate_git_hub_o_auth(
                ref_uri="ref_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.initiate_git_hub_o_auth(ref_uri=ref_uri, request_options=request_options)
        return _response.data

    async def exchange_google_code_for_tokens_api(
        self, *, request: PostAuthGoogleRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Exchange a Google OAuth authorization code for JWT tokens. Use this from SPAs/mobile apps instead of the web redirect flow.

        Parameters
        ----------
        request : PostAuthGoogleRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.exchange_google_code_for_tokens_api(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.exchange_google_code_for_tokens_api(
            request=request, request_options=request_options
        )
        return _response.data

    async def google_o_auth_callback_web(
        self, *, state: str, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Handle the Google OAuth redirect, exchange the code for tokens, and redirect to the frontend.

        Parameters
        ----------
        state : str
            OAuth state

        code : str
            Google authorization code

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.google_o_auth_callback_web(
                state="state",
                code="code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.google_o_auth_callback_web(
            state=state, code=code, request_options=request_options
        )
        return _response.data

    async def initiate_google_o_auth(
        self, *, ref_uri: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Generate an OAuth state and redirect the browser to Google's authorization page.

        Parameters
        ----------
        ref_uri : str
            Post-auth redirect URI (will be redirected to verbatim)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.initiate_google_o_auth(
                ref_uri="ref_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.initiate_google_o_auth(ref_uri=ref_uri, request_options=request_options)
        return _response.data

    async def logout_current_user(self, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Invalidate all sessions for the authenticated user.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.logout_current_user()


        asyncio.run(main())
        """
        _response = await self._raw_client.logout_current_user(request_options=request_options)
        return _response.data

    async def send_sms_verification_code(
        self, *, request: PostAuthSmsSendRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Send a one-time verification code to the given phone number. Rate-limited to 1 per 60 seconds.

        Parameters
        ----------
        request : PostAuthSmsSendRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.send_sms_verification_code(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_sms_verification_code(request=request, request_options=request_options)
        return _response.data

    async def verify_sms_code_and_authenticate(
        self, *, request: PostAuthSmsVerifyRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse:
        """
        Verify the SMS code and return JWT tokens. Creates a new user account if this phone is not registered.

        Parameters
        ----------
        request : PostAuthSmsVerifyRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAccountsInternalWebAuthResponse
            tokens set via Set-Cookie

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.auth.verify_sms_code_and_authenticate(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_sms_code_and_authenticate(
            request=request, request_options=request_options
        )
        return _response.data
