# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_payments_internal_web_wallet_transfer_request import (
    InternalPaymentsInternalWebWalletTransferRequest,
)

PostApiV1PaymentWalletsIdTransferRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalPaymentsInternalWebWalletTransferRequest
]
