# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_payments_internal_web_transfer_to_main_request import (
    InternalPaymentsInternalWebTransferToMainRequest,
)

PostApiV1PaymentWalletsIdTransferToMainRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalPaymentsInternalWebTransferToMainRequest
]
