# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_payments_internal_web_wallet_convert_request import (
    InternalPaymentsInternalWebWalletConvertRequest,
)

PostApiV1PaymentWalletsIdConvertCurrencyRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalPaymentsInternalWebWalletConvertRequest
]
