# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GithubComMktAgiAixInternalIamInternalDomainAccessGrant(UniversalBaseModel):
    created_at: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ] = None
    created_by: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="createdBy"), pydantic.Field(alias="createdBy")
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ] = None
    order_no: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="orderNo"), pydantic.Field(alias="orderNo")
    ] = None
    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    "grant" | "purchase"
    """

    user_id: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="userID"), pydantic.Field(alias="userID")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
