# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GithubComMktAgiAixInternalBulletinInternalDomainBulletin(UniversalBaseModel):
    body: typing.Optional[str] = None
    category: typing.Optional[str] = None
    created_at: typing.Optional[int] = None
    created_by: typing.Optional[int] = None
    expires_at: typing.Optional[int] = None
    id: typing.Optional[int] = None
    parent_id: typing.Optional[int] = None
    published_at: typing.Optional[int] = None
    section: typing.Optional[str] = None
    sort_order: typing.Optional[int] = None
    status: typing.Optional[str] = None
    summary: typing.Optional[str] = None
    title: typing.Optional[str] = None
    type: typing.Optional[str] = None
    updated_at: typing.Optional[int] = None
    updated_by: typing.Optional[int] = None
    version: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
