# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .github_com_mkt_agi_aix_internal_aigateway_internal_domain_model_capabilities import (
    GithubComMktAgiAixInternalAigatewayInternalDomainModelCapabilities,
)


class GithubComMktAgiAixInternalAigatewayInternalDomainModel(UniversalBaseModel):
    billing_mode: typing.Optional[str] = None
    cache_hit_price: typing.Optional[float] = None
    capabilities: typing.Optional[GithubComMktAgiAixInternalAigatewayInternalDomainModelCapabilities] = None
    created_at: typing.Optional[int] = None
    currency: typing.Optional[str] = None
    description: typing.Optional[str] = None
    enabled: typing.Optional[bool] = None
    id: typing.Optional[int] = None
    input_price: typing.Optional[float] = None
    is_default: typing.Optional[bool] = None
    listed_at: typing.Optional[int] = None
    max_output_tokens: typing.Optional[int] = None
    name: typing.Optional[str] = None
    output_price: typing.Optional[float] = None
    provider_id: typing.Optional[int] = None
    updated_at: typing.Optional[int] = None
    upstream_name: typing.Optional[str] = None
    user_id: typing.Optional[int] = None
    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    "private" | "public" | "filter"
    """

    wallet_id: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
