# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GithubComMktAgiAixInternalMessagingInternalDomainConversationSummary(UniversalBaseModel):
    created_at: typing.Optional[int] = None
    created_by: typing.Optional[int] = None
    id: typing.Optional[int] = None
    last_message: typing.Optional[str] = None
    last_msg_at: typing.Optional[int] = None
    max_seq: typing.Optional[int] = None
    read_seq: typing.Optional[int] = None
    synced_seq: typing.Optional[int] = None
    title: typing.Optional[str] = None
    type: typing.Optional[str] = None
    uid: typing.Optional[str] = None
    unread_count: typing.Optional[int] = None
    updated_at: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
