# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class GithubComMktAgiAixInternalAigatewayInternalDomainAiSession(UniversalBaseModel):
    created_at: typing.Optional[int] = None
    deleted_at: typing.Optional[int] = None
    id: typing.Optional[str] = None
    subject_id: typing.Optional[int] = None
    subject_type: typing.Optional[str] = None
    title: typing.Optional[str] = None
    updated_at: typing.Optional[int] = None
    uuid_: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
