# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GithubComMktAgiAixInternalMessagingInternalDomainMessage(UniversalBaseModel):
    content: typing.Optional[str] = None
    content_type: typing.Optional[str] = None
    conv_id: typing.Optional[int] = None
    created_at: typing.Optional[int] = None
    id: typing.Optional[int] = None
    mentioned_user_ids: typing.Optional[typing.List[int]] = None
    metadata: typing.Optional[str] = None
    reply_to_seq: typing.Optional[int] = None
    sender_id: typing.Optional[int] = None
    seq: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
