# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalMessagingInternalWebRegisterDeviceReq(UniversalBaseModel):
    """
    Request to register a push notification device for the current user.
    """

    device_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    DeviceID is the unique identifier of the device.
    """

    platform: typing.Optional[str] = pydantic.Field(default=None)
    """
    Platform is the device platform (e.g. "ios", "android", "web").
    """

    push_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    PushToken is the push notification service token for the device.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
