# This file was auto-generated by Fern from our API Definition.

import typing

InternalAigatewayInternalWebUserProviderRequestProtocol = typing.Union[
    typing.Literal["openai", "anthropic"], typing.Any
]
