# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebUserSecretValueResponse(UniversalBaseModel):
    """
    User secret metadata including the decrypted value.
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    CreatedAt is the Unix timestamp of when the secret was created.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description is a human-readable description of the secret.
    """

    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Key is the unique key identifying this secret within the user's namespace.
    """

    updated_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    UpdatedAt is the Unix timestamp of when the secret was last updated.
    """

    user_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    UserID is the ID of the user who owns this secret.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value is the decrypted secret value.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
