# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .internal_payments_internal_web_balance_transaction_v2response import (
    InternalPaymentsInternalWebBalanceTransactionV2Response,
)


class InternalPaymentsInternalWebWalletTransferV2Response(UniversalBaseModel):
    """
    Transfer is the optional transfer detail.
    """

    amount: typing.Optional[str] = pydantic.Field(default=None)
    """
    Amount is the transferred amount as a string.
    """

    balance_transactions: typing.Optional[typing.List[InternalPaymentsInternalWebBalanceTransactionV2Response]] = (
        pydantic.Field(default=None)
    )
    """
    BalanceTransactions lists the associated ledger entries.
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    CreatedAt is the creation Unix timestamp.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency is the ISO currency code.
    """

    from_wallet_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    FromWalletID is the source wallet ID.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Note is an optional human-readable note.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Status is the transfer status.
    """

    to_wallet_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ToWalletID is the destination wallet ID.
    """

    transfer_no: typing.Optional[int] = pydantic.Field(default=None)
    """
    TransferNo is the unique transfer number.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
