# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAigatewayInternalWebUserProviderResponse(UniversalBaseModel):
    """
    User provider with masked API key.
    """

    api_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    APIKey is the masked API key (last 4 characters visible).
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    BaseURL is the API base URL.
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    CreatedAt is the creation timestamp (Unix seconds).
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enabled indicates whether the provider is active.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ID is the provider ID.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name is the provider display name.
    """

    protocol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Protocol is the API protocol.
    """

    updated_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    UpdatedAt is the last update timestamp (Unix seconds).
    """

    user_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    UserID is the owner user ID.
    """

    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    Visibility is the provider visibility.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
