# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalWisdomInternalWebUpdateCommunityRequest(UniversalBaseModel):
    defencer: typing.Optional[str] = pydantic.Field(default=None)
    """
    防御
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    描述
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    指令
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    标签
    """

    listing_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    上架状态
    """

    price: typing.Optional[float] = pydantic.Field(default=None)
    """
    价格
    """

    pricing_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    定价模型
    """

    promise: typing.Optional[str] = pydantic.Field(default=None)
    """
    承诺
    """

    props: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    扩展属性
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    标识
    """

    style: typing.Optional[str] = pydantic.Field(default=None)
    """
    风格
    """

    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    可见性
    """

    want_capability: typing.Optional[str] = pydantic.Field(default=None)
    """
    期望能力
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
