# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAigatewayInternalWebLlmReqLogItem(UniversalBaseModel):
    cache_hit_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    CacheHitTokens 是 prompt 缓存命中的 token 数，按 cache_hit_price 计费，不参与 input_price 计费。
    """

    completion_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    CompletionTokens is the number of completion tokens.
    """

    cost: typing.Optional[float] = pydantic.Field(default=None)
    """
    Cost is the request cost (yuan).
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    CreatedAt is the creation timestamp (Unix seconds).
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ID is the log entry ID.
    """

    latency_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    LatencyMs is the total request latency in milliseconds.
    """

    model_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ModelID is the model used.
    """

    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    PromptTokens is the number of prompt tokens.
    """

    provider_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    ProviderID is the provider used.
    """

    request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    RequestID 是请求关联 ID（来自 X-Request-ID header 或自动生成），用于跨系统链路追踪。
    """

    status: typing.Optional[int] = pydantic.Field(default=None)
    """
    Status is the HTTP status code.
    """

    stream: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Stream indicates whether this was a streaming request.
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    TotalTokens is the total token count.
    """

    tps: typing.Optional[float] = pydantic.Field(default=None)
    """
    TPS is the tokens per second throughput.
    """

    ttft_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    TTFTMs is the time to first token in milliseconds (0 for non-streaming).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
