# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalIamInternalWebAddFilterRequest(UniversalBaseModel):
    """
    Request body for adding a visibility filter.
    """

    resource_id: int = pydantic.Field()
    """
    resource primary key
    """

    resource_type: str = pydantic.Field()
    """
    "aigateway_model" | "aigateway_route" | "files_file"
    """

    user_id: int = pydantic.Field()
    """
    target user ID
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
