# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel, update_forward_refs


class InternalCommentsInternalWebCommentTreeVo(UniversalBaseModel):
    data: typing.Optional[typing.List["GithubComMktAgiAixInternalCommentsInternalDomainCommentNode"]] = None
    next_cursor: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .github_com_mkt_agi_aix_internal_comments_internal_domain_comment_node import (
    GithubComMktAgiAixInternalCommentsInternalDomainCommentNode,
)  # noqa: E402, I001

update_forward_refs(
    InternalCommentsInternalWebCommentTreeVo,
    GithubComMktAgiAixInternalCommentsInternalDomainCommentNode=GithubComMktAgiAixInternalCommentsInternalDomainCommentNode,
)
