# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalMessagingInternalWebSendMessageReq(UniversalBaseModel):
    """
    Request to send a message in a conversation.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Content is the message body text.
    """

    content_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    ContentType indicates the message format (e.g. "text", "markdown").
    """

    mentioned_user_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    MentionedUserIDs is the list of user IDs @-mentioned in this message.
    Optional, defaults to empty when not provided.
    @Interaction 客户端传入被 @ 的用户 ID 列表（由前端 @ 选人组件生成）。空数组或无此字段表示无提及。后续 AI 网关据此判断是否 @了 AI 从而触发 LLM 调用。
    """

    metadata: typing.Optional[str] = pydantic.Field(default=None)
    """
    Metadata carries optional structured metadata attached to the message.
    """

    reply_to_seq: typing.Optional[int] = pydantic.Field(default=None)
    """
    ReplyToSeq references the sequence number of the message being replied to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
