# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAigatewayInternalWebUserModelRequest(UniversalBaseModel):
    billing_mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    BillingMode is the billing mode: "token" (default) or "per_request".
    """

    cache_hit_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    CacheHitPrice is the cache hit price per 1M tokens (CNY). 0 means same as input_price.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency is the billing currency (CNY or USD, default CNY).
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description is an optional human-readable description.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enabled controls whether the model is active.
    """

    input_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    InputPrice is the price per 1M input tokens (CNY).
    """

    is_default: typing.Optional[bool] = pydantic.Field(default=None)
    """
    IsDefault indicates whether to set this as the user's default model.
    """

    max_output_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    MaxOutputTokens is the maximum output token count (0=system default).
    """

    name: str = pydantic.Field()
    """
    Name is the user-facing model identifier.
    """

    output_price: typing.Optional[float] = pydantic.Field(default=None)
    """
    OutputPrice is the price per 1M output tokens (CNY).
    """

    provider_id: int = pydantic.Field()
    """
    ProviderID is the associated provider ID.
    """

    upstream_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    UpstreamName is the upstream provider's model name (overrides Name if set).
    """

    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    Visibility is the model visibility (private or public).
    """

    wallet_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    WalletID is the optional bound wallet ID for receiving earnings.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
