# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebCaptchaGenerateResponse(UniversalBaseModel):
    """
    Captcha token and base64-encoded PNG image.
    """

    image_base64: typing.Optional[str] = pydantic.Field(default=None)
    """
    ImageB64 is the base64-encoded PNG captcha image.
    """

    token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Token is the captcha verification token.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
