# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebAvatarUploadUrlResponse(UniversalBaseModel):
    """
    Presigned upload URL, storage key and public URL.
    """

    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Key is the storage key for the uploaded file.
    """

    public_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    PublicURL is the public CDN URL of the avatar after upload.
    """

    upload_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    UploadURL is the presigned S3 URL for direct browser upload.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
