# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebEmailSendRequest(UniversalBaseModel):
    """
    Email address with optional captcha verification.
    """

    captcha_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    CaptchaCode is the user's input for the captcha challenge.
    """

    captcha_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    CaptchaToken is an optional captcha verification token from the frontend widget.
    """

    email: str = pydantic.Field()
    """
    Email is the email address to send the verification code to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
