# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .internal_wisdom_internal_web_relation_response import InternalWisdomInternalWebRelationResponse
from .internal_wisdom_internal_web_wisdom_response import InternalWisdomInternalWebWisdomResponse


class InternalWisdomInternalWebGraphResponse(UniversalBaseModel):
    edges: typing.Optional[typing.List[InternalWisdomInternalWebRelationResponse]] = pydantic.Field(default=None)
    """
    边列表
    """

    nodes: typing.Optional[typing.List[InternalWisdomInternalWebWisdomResponse]] = pydantic.Field(default=None)
    """
    节点列表
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
