# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebUpsertSecretReq(UniversalBaseModel):
    """
    Secret value and description for create/update.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description is an optional human-readable description of the secret (max 8KiB).
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value is the secret value to encrypt and store (max 64KiB).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
