# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalMessagingInternalWebCreateConversationReq(UniversalBaseModel):
    """
    Request to create a new conversation with participants.
    """

    participant_ids: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    ParticipantIDs lists the initial participant user IDs to add.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title is the conversation display title.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Type is the conversation type (e.g. "direct", "group").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
