# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalWisdomInternalWebCommunityResponse(UniversalBaseModel):
    confidence: typing.Optional[float] = pydantic.Field(default=None)
    """
    置信度
    """

    created_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    创建时间
    """

    defencer: typing.Optional[str] = pydantic.Field(default=None)
    """
    防御
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    描述
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    主键
    """

    instructions: typing.Optional[str] = pydantic.Field(default=None)
    """
    指令
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    标签
    """

    member_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    成员数
    """

    modularity: typing.Optional[float] = pydantic.Field(default=None)
    """
    模块度
    """

    promise: typing.Optional[str] = pydantic.Field(default=None)
    """
    承诺
    """

    props: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    扩展属性
    """

    reflector: typing.Optional[str] = pydantic.Field(default=None)
    """
    反思
    """

    resolution: typing.Optional[float] = pydantic.Field(default=None)
    """
    决议值
    """

    slug: typing.Optional[str] = pydantic.Field(default=None)
    """
    标识
    """

    style: typing.Optional[str] = pydantic.Field(default=None)
    """
    风格
    """

    updated_at: typing.Optional[int] = pydantic.Field(default=None)
    """
    更新时间
    """

    user_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    所属用户
    """

    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    可见性
    """

    want_capability: typing.Optional[str] = pydantic.Field(default=None)
    """
    期望能力
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
