# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAccountsInternalWebUserPreferencesReq(UniversalBaseModel):
    """
    Preferences is the user preference object for partial update.
    """

    lang: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lang is the user's preferred language (e.g., "en", "zh").
    """

    theme: typing.Optional[str] = pydantic.Field(default=None)
    """
    Theme is the user's preferred UI theme (e.g., "light", "dark").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
