# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalAigatewayInternalWebSellerRevenueItem(UniversalBaseModel):
    calls_today: typing.Optional[int] = None
    calls_total: typing.Optional[int] = None
    model_id: typing.Optional[int] = None
    model_name: typing.Optional[str] = None
    revenue_today: typing.Optional[float] = None
    revenue_total: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
