# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InternalFilesInternalWebIngestUrlRequest(UniversalBaseModel):
    biz_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    business context ID
    """

    dir_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    target directory path, defaults to "/"
    """

    filename: str = pydantic.Field()
    """
    target filename
    """

    url: str = pydantic.Field()
    """
    source URL to download
    """

    visibility: typing.Optional[str] = pydantic.Field(default=None)
    """
    "private" | "public" | "filter"
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
