# This file was auto-generated by Fern from our API Definition.

import typing

from .internal_accounts_internal_web_setup_request import InternalAccountsInternalWebSetupRequest

PostSetupRequest = typing.Union[typing.Dict[str, typing.Any], InternalAccountsInternalWebSetupRequest]
