# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_bugreports_internal_web_update_bug_report_request import (
    InternalBugreportsInternalWebUpdateBugReportRequest,
)

PatchAdminBugReportsIdRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalBugreportsInternalWebUpdateBugReportRequest
]
