# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_any import GithubComMktAgiAixInternalPkgGinxResultAny
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_github_com_mkt_agi_aix_internal_aigateway_internal_domain_ai_session import (
    GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_github_com_mkt_agi_aix_internal_aigateway_internal_domain_ai_session import (
    GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession,
)
from .raw_client import AsyncRawSessionsClient, RawSessionsClient
from .types.patch_gateway_sessions_id_request_body import PatchGatewaySessionsIdRequestBody
from .types.post_gateway_sessions_request import PostGatewaySessionsRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def list_ai_sessions(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession:
        """
        Return paginated list of AI chat sessions for the current user

        Parameters
        ----------
        cursor : typing.Optional[str]
            Pagination cursor

        limit : typing.Optional[int]
            Page size (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.sessions.list_ai_sessions()
        """
        _response = self._raw_client.list_ai_sessions(cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    def create_ai_session(
        self, *, request: PostGatewaySessionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession:
        """
        Create a new AI chat session for the current user

        Parameters
        ----------
        request : PostGatewaySessionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession
            Created

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.sessions.create_ai_session(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create_ai_session(request=request, request_options=request_options)
        return _response.data

    def delete_ai_session(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Soft-delete an AI chat session

        Parameters
        ----------
        id : int
            Session ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.sessions.delete_ai_session(
            id=1,
        )
        """
        _response = self._raw_client.delete_ai_session(id, request_options=request_options)
        return _response.data

    def update_ai_session(
        self,
        id: int,
        *,
        request: PatchGatewaySessionsIdRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Update session title or metadata

        Parameters
        ----------
        id : int
            Session ID

        request : PatchGatewaySessionsIdRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.sessions.update_ai_session(
            id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.update_ai_session(id, request=request, request_options=request_options)
        return _response.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def list_ai_sessions(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession:
        """
        Return paginated list of AI chat sessions for the current user

        Parameters
        ----------
        cursor : typing.Optional[str]
            Pagination cursor

        limit : typing.Optional[int]
            Page size (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalAigatewayInternalDomainAiSession
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.list_ai_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_ai_sessions(cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    async def create_ai_session(
        self, *, request: PostGatewaySessionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession:
        """
        Create a new AI chat session for the current user

        Parameters
        ----------
        request : PostGatewaySessionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalAigatewayInternalDomainAiSession
            Created

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.create_ai_session(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_ai_session(request=request, request_options=request_options)
        return _response.data

    async def delete_ai_session(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Soft-delete an AI chat session

        Parameters
        ----------
        id : int
            Session ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.delete_ai_session(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_ai_session(id, request_options=request_options)
        return _response.data

    async def update_ai_session(
        self,
        id: int,
        *,
        request: PatchGatewaySessionsIdRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Update session title or metadata

        Parameters
        ----------
        id : int
            Session ID

        request : PatchGatewaySessionsIdRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sessions.update_ai_session(
                id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_ai_session(id, request=request, request_options=request_options)
        return _response.data
