# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_comments_internal_web_create_comment_req import InternalCommentsInternalWebCreateCommentReq

PostApiV1CommentsRequest = typing.Union[typing.Dict[str, typing.Any], InternalCommentsInternalWebCreateCommentReq]
