# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_comments_internal_web_update_comment_req import InternalCommentsInternalWebUpdateCommentReq

PutApiV1CommentsIdRequestBody = typing.Union[typing.Dict[str, typing.Any], InternalCommentsInternalWebUpdateCommentReq]
