# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_aigateway_internal_web_test_model_request import InternalAigatewayInternalWebTestModelRequest

PostGatewayUserIdTestModelRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalAigatewayInternalWebTestModelRequest
]
