# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_any import GithubComMktAgiAixInternalPkgGinxResultAny
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_github_com_mkt_agi_aix_internal_iam_access_grant import (
    GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_aigateway_internal_web_user_route_response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_aigateway_internal_web_user_route_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse,
)
from .raw_client import AsyncRawUserRoutesClient, RawUserRoutesClient
from .types.post_gateway_user_id_routes_id_grants_request_body import PostGatewayUserIdRoutesIdGrantsRequestBody
from .types.post_gateway_user_id_routes_request_body import PostGatewayUserIdRoutesRequestBody

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UserRoutesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserRoutesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserRoutesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserRoutesClient
        """
        return self._raw_client

    def list_user_model_routes(
        self, user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse:
        """
        Return all routes for the authenticated user

        Parameters
        ----------
        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.list_user_model_routes(
            user_id=1,
        )
        """
        _response = self._raw_client.list_user_model_routes(user_id, request_options=request_options)
        return _response.data

    def create_user_model_route(
        self,
        user_id: int,
        *,
        request: PostGatewayUserIdRoutesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse:
        """
        Create a user-scoped model_prefix → provider routing override.

        Parameters
        ----------
        user_id : int
            User ID

        request : PostGatewayUserIdRoutesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
            Created

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.create_user_model_route(
            user_id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create_user_model_route(user_id, request=request, request_options=request_options)
        return _response.data

    def get_user_model_route(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse:
        """
        Return a single route by ID

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.get_user_model_route(
            user_id=1,
            id=1,
        )
        """
        _response = self._raw_client.get_user_model_route(user_id, id, request_options=request_options)
        return _response.data

    def delete_user_model_route(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Delete a user route by ID

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.delete_user_model_route(
            user_id=1,
            id=1,
        )
        """
        _response = self._raw_client.delete_user_model_route(user_id, id, request_options=request_options)
        return _response.data

    def list_route_access_grants(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant:
        """
        Return all access grants for a route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.list_route_access_grants(
            user_id=1,
            id=1,
        )
        """
        _response = self._raw_client.list_route_access_grants(user_id, id, request_options=request_options)
        return _response.data

    def grant_route_access(
        self,
        user_id: int,
        id: int,
        *,
        request: PostGatewayUserIdRoutesIdGrantsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Grant a user access to a private route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request : PostGatewayUserIdRoutesIdGrantsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            Created

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.grant_route_access(
            user_id=1,
            id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.grant_route_access(user_id, id, request=request, request_options=request_options)
        return _response.data

    def revoke_route_access(
        self, user_id: int, id: int, target_user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Revoke a user's access to a route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        target_user_id : int
            Target user ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            No Content

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_routes.revoke_route_access(
            user_id=1,
            id=1,
            target_user_id=1,
        )
        """
        _response = self._raw_client.revoke_route_access(user_id, id, target_user_id, request_options=request_options)
        return _response.data


class AsyncUserRoutesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserRoutesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserRoutesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserRoutesClient
        """
        return self._raw_client

    async def list_user_model_routes(
        self, user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse:
        """
        Return all routes for the authenticated user

        Parameters
        ----------
        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalAigatewayInternalWebUserRouteResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.list_user_model_routes(
                user_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_user_model_routes(user_id, request_options=request_options)
        return _response.data

    async def create_user_model_route(
        self,
        user_id: int,
        *,
        request: PostGatewayUserIdRoutesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse:
        """
        Create a user-scoped model_prefix → provider routing override.

        Parameters
        ----------
        user_id : int
            User ID

        request : PostGatewayUserIdRoutesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
            Created

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.create_user_model_route(
                user_id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_user_model_route(
            user_id, request=request, request_options=request_options
        )
        return _response.data

    async def get_user_model_route(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse:
        """
        Return a single route by ID

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebUserRouteResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.get_user_model_route(
                user_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_user_model_route(user_id, id, request_options=request_options)
        return _response.data

    async def delete_user_model_route(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Delete a user route by ID

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.delete_user_model_route(
                user_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_user_model_route(user_id, id, request_options=request_options)
        return _response.data

    async def list_route_access_grants(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant:
        """
        Return all access grants for a route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.list_route_access_grants(
                user_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_route_access_grants(user_id, id, request_options=request_options)
        return _response.data

    async def grant_route_access(
        self,
        user_id: int,
        id: int,
        *,
        request: PostGatewayUserIdRoutesIdGrantsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Grant a user access to a private route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        request : PostGatewayUserIdRoutesIdGrantsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            Created

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.grant_route_access(
                user_id=1,
                id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.grant_route_access(
            user_id, id, request=request, request_options=request_options
        )
        return _response.data

    async def revoke_route_access(
        self, user_id: int, id: int, target_user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Revoke a user's access to a route

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Route ID

        target_user_id : int
            Target user ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            No Content

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_routes.revoke_route_access(
                user_id=1,
                id=1,
                target_user_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_route_access(
            user_id, id, target_user_id, request_options=request_options
        )
        return _response.data
