# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_aigateway_internal_web_marketplace_list_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebMarketplaceListResponse,
)
from .raw_client import AsyncRawMarketplaceClient, RawMarketplaceClient


class MarketplaceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMarketplaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMarketplaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMarketplaceClient
        """
        return self._raw_client

    def list_marketplace_models(
        self,
        *,
        search: typing.Optional[str] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebMarketplaceListResponse:
        """
        Returns paginated marketplace models with search, price filter, and sort.

        Parameters
        ----------
        search : typing.Optional[str]
            Search by name or description

        min_price : typing.Optional[float]
            Minimum output price filter

        max_price : typing.Optional[float]
            Maximum output price filter

        sort : typing.Optional[str]
            Sort field: listed_at, call_count, output_price (default listed_at)

        order : typing.Optional[str]
            Sort order: asc, desc (default desc)

        page : typing.Optional[int]
            Page number (default 1)

        limit : typing.Optional[int]
            Page size (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebMarketplaceListResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.marketplace.list_marketplace_models()
        """
        _response = self._raw_client.list_marketplace_models(
            search=search,
            min_price=min_price,
            max_price=max_price,
            sort=sort,
            order=order,
            page=page,
            limit=limit,
            request_options=request_options,
        )
        return _response.data


class AsyncMarketplaceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMarketplaceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMarketplaceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMarketplaceClient
        """
        return self._raw_client

    async def list_marketplace_models(
        self,
        *,
        search: typing.Optional[str] = None,
        min_price: typing.Optional[float] = None,
        max_price: typing.Optional[float] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebMarketplaceListResponse:
        """
        Returns paginated marketplace models with search, price filter, and sort.

        Parameters
        ----------
        search : typing.Optional[str]
            Search by name or description

        min_price : typing.Optional[float]
            Minimum output price filter

        max_price : typing.Optional[float]
            Maximum output price filter

        sort : typing.Optional[str]
            Sort field: listed_at, call_count, output_price (default listed_at)

        order : typing.Optional[str]
            Sort order: asc, desc (default desc)

        page : typing.Optional[int]
            Page number (default 1)

        limit : typing.Optional[int]
            Page size (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalAigatewayInternalWebMarketplaceListResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.marketplace.list_marketplace_models()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_marketplace_models(
            search=search,
            min_price=min_price,
            max_price=max_price,
            sort=sort,
            order=order,
            page=page,
            limit=limit,
            request_options=request_options,
        )
        return _response.data
