# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_github_com_mkt_agi_aix_internal_messaging_internal_domain_message import (
    GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalMessagingInternalDomainMessage,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_github_com_mkt_agi_aix_internal_messaging_internal_domain_message import (
    GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalMessagingInternalDomainMessage,
)
from .raw_client import AsyncRawMessagesClient, RawMessagesClient
from .types.post_messaging_conversations_conv_id_messages_request_body import (
    PostMessagingConversationsConvIdMessagesRequestBody,
)
from .types.post_messaging_read_request import PostMessagingReadRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMessagesClient
        """
        return self._raw_client

    def get_messages(
        self,
        conv_id: int,
        *,
        after_seq: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalMessagingInternalDomainMessage:
        """
        Retrieve messages in a conversation

        Parameters
        ----------
        conv_id : int
            Conversation ID

        after_seq : typing.Optional[int]
            Only messages after this sequence number

        limit : typing.Optional[int]
            Page limit (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalMessagingInternalDomainMessage
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.messages.get_messages(
            conv_id=1,
        )
        """
        _response = self._raw_client.get_messages(
            conv_id, after_seq=after_seq, limit=limit, request_options=request_options
        )
        return _response.data

    def send_message(
        self,
        conv_id: int,
        *,
        request: PostMessagingConversationsConvIdMessagesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalMessagingInternalDomainMessage:
        """
        Send a message in a conversation

        Parameters
        ----------
        conv_id : int
            Conversation ID

        request : PostMessagingConversationsConvIdMessagesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalMessagingInternalDomainMessage
            Created

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.messages.send_message(
            conv_id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.send_message(conv_id, request=request, request_options=request_options)
        return _response.data

    def mark_messages_as_read(
        self, *, request: PostMessagingReadRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Mark messages as read up to the given sequence number

        Parameters
        ----------
        request : PostMessagingReadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.messages.mark_messages_as_read(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.mark_messages_as_read(request=request, request_options=request_options)
        return _response.data


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMessagesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMessagesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMessagesClient
        """
        return self._raw_client

    async def get_messages(
        self,
        conv_id: int,
        *,
        after_seq: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalMessagingInternalDomainMessage:
        """
        Retrieve messages in a conversation

        Parameters
        ----------
        conv_id : int
            Conversation ID

        after_seq : typing.Optional[int]
            Only messages after this sequence number

        limit : typing.Optional[int]
            Page limit (default 20, max 100)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalMessagingInternalDomainMessage
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.get_messages(
                conv_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_messages(
            conv_id, after_seq=after_seq, limit=limit, request_options=request_options
        )
        return _response.data

    async def send_message(
        self,
        conv_id: int,
        *,
        request: PostMessagingConversationsConvIdMessagesRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalMessagingInternalDomainMessage:
        """
        Send a message in a conversation

        Parameters
        ----------
        conv_id : int
            Conversation ID

        request : PostMessagingConversationsConvIdMessagesRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultGithubComMktAgiAixInternalMessagingInternalDomainMessage
            Created

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.send_message(
                conv_id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_message(conv_id, request=request, request_options=request_options)
        return _response.data

    async def mark_messages_as_read(
        self, *, request: PostMessagingReadRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Mark messages as read up to the given sequence number

        Parameters
        ----------
        request : PostMessagingReadRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.messages.mark_messages_as_read(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.mark_messages_as_read(request=request, request_options=request_options)
        return _response.data
