# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_iam_internal_web_create_api_key_request import InternalIamInternalWebCreateApiKeyRequest

PostIamApiKeysRequest = typing.Union[typing.Dict[str, typing.Any], InternalIamInternalWebCreateApiKeyRequest]
