# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_any import GithubComMktAgiAixInternalPkgGinxResultAny
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_github_com_mkt_agi_aix_internal_iam_access_grant import (
    GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant,
)
from .raw_client import AsyncRawUserModelsClient, RawUserModelsClient
from .types.post_gateway_user_id_models_id_grants_request_body import PostGatewayUserIdModelsIdGrantsRequestBody

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UserModelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserModelsClient
        """
        return self._raw_client

    def list_model_access_grants(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant:
        """
        Return all access grants for a model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_models.list_model_access_grants(
            user_id=1,
            id=1,
        )
        """
        _response = self._raw_client.list_model_access_grants(user_id, id, request_options=request_options)
        return _response.data

    def grant_model_access(
        self,
        user_id: int,
        id: int,
        *,
        request: PostGatewayUserIdModelsIdGrantsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Grant a user access to a private model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        request : PostGatewayUserIdModelsIdGrantsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            Created

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_models.grant_model_access(
            user_id=1,
            id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.grant_model_access(user_id, id, request=request, request_options=request_options)
        return _response.data

    def revoke_model_access(
        self, user_id: int, id: int, target_user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Revoke a user's access to a model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        target_user_id : int
            Target user ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            No Content

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.user_models.revoke_model_access(
            user_id=1,
            id=1,
            target_user_id=1,
        )
        """
        _response = self._raw_client.revoke_model_access(user_id, id, target_user_id, request_options=request_options)
        return _response.data


class AsyncUserModelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserModelsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserModelsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserModelsClient
        """
        return self._raw_client

    async def list_model_access_grants(
        self, user_id: int, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant:
        """
        Return all access grants for a model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayGithubComMktAgiAixInternalIamAccessGrant
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_models.list_model_access_grants(
                user_id=1,
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_model_access_grants(user_id, id, request_options=request_options)
        return _response.data

    async def grant_model_access(
        self,
        user_id: int,
        id: int,
        *,
        request: PostGatewayUserIdModelsIdGrantsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Grant a user access to a private model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        request : PostGatewayUserIdModelsIdGrantsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            Created

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_models.grant_model_access(
                user_id=1,
                id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.grant_model_access(
            user_id, id, request=request, request_options=request_options
        )
        return _response.data

    async def revoke_model_access(
        self, user_id: int, id: int, target_user_id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultAny:
        """
        Revoke a user's access to a model

        Parameters
        ----------
        user_id : int
            User ID

        id : int
            Model ID

        target_user_id : int
            Target user ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultAny
            No Content

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user_models.revoke_model_access(
                user_id=1,
                id=1,
                target_user_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_model_access(
            user_id, id, target_user_id, request_options=request_options
        )
        return _response.data
