# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_notifications_internal_web_admin_send_req import InternalNotificationsInternalWebAdminSendReq

PostApiV1AdminNotificationsRequest = typing.Union[
    typing.Dict[str, typing.Any], InternalNotificationsInternalWebAdminSendReq
]
