# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_notifications_internal_web_set_preference_req import (
    InternalNotificationsInternalWebSetPreferenceReq,
)

PutApiV1NotificationsPreferencesRequest = typing.Union[
    typing.Dict[str, typing.Any], InternalNotificationsInternalWebSetPreferenceReq
]
