# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_wisdom_internal_web_add_relation_request import InternalWisdomInternalWebAddRelationRequest

PostWisdomIdRelationsRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalWisdomInternalWebAddRelationRequest
]
