# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_iam_internal_web_api_key_response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_uint import (
    GithubComMktAgiAixInternalPkgGinxResultArrayUint,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_iam_internal_web_create_api_key_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,
)
from .raw_client import AsyncRawIamClient, RawIamClient
from .types.post_iam_api_keys_request import PostIamApiKeysRequest
from .types.post_iam_visibility_filters_request import PostIamVisibilityFiltersRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIamClient
        """
        return self._raw_client

    def list_api_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse:
        """
        List API key metadata for the authenticated user. Raw keys and hashes are never returned.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.list_api_keys()
        """
        _response = self._raw_client.list_api_keys(request_options=request_options)
        return _response.data

    def create_api_key(
        self, *, request: PostIamApiKeysRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse:
        """
        Create an API key for the authenticated user. The raw API key is returned only once in this response.

        Parameters
        ----------
        request : PostIamApiKeysRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.create_api_key(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create_api_key(request=request, request_options=request_options)
        return _response.data

    def revoke_api_key(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revoke an API key owned by the authenticated user.

        Parameters
        ----------
        id : int
            API key ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.revoke_api_key(
            id=1,
        )
        """
        _response = self._raw_client.revoke_api_key(id, request_options=request_options)
        return _response.data

    def list_visibility_filters(
        self, *, resource_type: str, resource_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayUint:
        """
        列出资源的可见性过滤器用户列表。返回被添加到可见性白名单中的用户 ID。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayUint
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.list_visibility_filters(
            resource_type="resource_type",
            resource_id=1,
        )
        """
        _response = self._raw_client.list_visibility_filters(
            resource_type=resource_type, resource_id=resource_id, request_options=request_options
        )
        return _response.data

    def add_visibility_filter(
        self, *, request: PostIamVisibilityFiltersRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        添加可见性过滤器，将指定用户添加到资源的可见性白名单中。

        Parameters
        ----------
        request : PostIamVisibilityFiltersRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.add_visibility_filter(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.add_visibility_filter(request=request, request_options=request_options)
        return _response.data

    def remove_visibility_filter(
        self,
        resource_type: str,
        resource_id: int,
        user_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        移除可见性过滤器，将指定用户从资源的可见性白名单中移除。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.iam.remove_visibility_filter(
            resource_type="resource_type",
            resource_id=1,
            user_id=1,
        )
        """
        _response = self._raw_client.remove_visibility_filter(
            resource_type, resource_id, user_id, request_options=request_options
        )
        return _response.data


class AsyncIamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIamClient
        """
        return self._raw_client

    async def list_api_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse:
        """
        List API key metadata for the authenticated user. Raw keys and hashes are never returned.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.list_api_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_api_keys(request_options=request_options)
        return _response.data

    async def create_api_key(
        self, *, request: PostIamApiKeysRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse:
        """
        Create an API key for the authenticated user. The raw API key is returned only once in this response.

        Parameters
        ----------
        request : PostIamApiKeysRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.create_api_key(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_api_key(request=request, request_options=request_options)
        return _response.data

    async def revoke_api_key(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Revoke an API key owned by the authenticated user.

        Parameters
        ----------
        id : int
            API key ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.revoke_api_key(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_api_key(id, request_options=request_options)
        return _response.data

    async def list_visibility_filters(
        self, *, resource_type: str, resource_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayUint:
        """
        列出资源的可见性过滤器用户列表。返回被添加到可见性白名单中的用户 ID。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayUint
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.list_visibility_filters(
                resource_type="resource_type",
                resource_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_visibility_filters(
            resource_type=resource_type, resource_id=resource_id, request_options=request_options
        )
        return _response.data

    async def add_visibility_filter(
        self, *, request: PostIamVisibilityFiltersRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        添加可见性过滤器，将指定用户添加到资源的可见性白名单中。

        Parameters
        ----------
        request : PostIamVisibilityFiltersRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.add_visibility_filter(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_visibility_filter(request=request, request_options=request_options)
        return _response.data

    async def remove_visibility_filter(
        self,
        resource_type: str,
        resource_id: int,
        user_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        移除可见性过滤器，将指定用户从资源的可见性白名单中移除。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.iam.remove_visibility_filter(
                resource_type="resource_type",
                resource_id=1,
                user_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_visibility_filter(
            resource_type, resource_id, user_id, request_options=request_options
        )
        return _response.data
