# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_code_resp import GithubComMktAgiAixInternalPkgGinxCodeResp
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_iam_internal_web_api_key_response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_uint import (
    GithubComMktAgiAixInternalPkgGinxResultArrayUint,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_iam_internal_web_create_api_key_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,
)
from .types.post_iam_api_keys_request import PostIamApiKeysRequest
from .types.post_iam_visibility_filters_request import PostIamVisibilityFiltersRequest
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawIamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_api_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse]:
        """
        List API key metadata for the authenticated user. Raw keys and hashes are never returned.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "iam/api-keys",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_api_key(
        self, *, request: PostIamApiKeysRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse]:
        """
        Create an API key for the authenticated user. The raw API key is returned only once in this response.

        Parameters
        ----------
        request : PostIamApiKeysRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "iam/api-keys",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostIamApiKeysRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def revoke_api_key(self, id: int, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[None]:
        """
        Revoke an API key owned by the authenticated user.

        Parameters
        ----------
        id : int
            API key ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"iam/api-keys/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_visibility_filters(
        self, *, resource_type: str, resource_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayUint]:
        """
        列出资源的可见性过滤器用户列表。返回被添加到可见性白名单中的用户 ID。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayUint]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "iam/visibility-filters",
            method="GET",
            params={
                "resource_type": resource_type,
                "resource_id": resource_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayUint,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayUint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_visibility_filter(
        self, *, request: PostIamVisibilityFiltersRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        添加可见性过滤器，将指定用户添加到资源的可见性白名单中。

        Parameters
        ----------
        request : PostIamVisibilityFiltersRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            "iam/visibility-filters",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostIamVisibilityFiltersRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_visibility_filter(
        self,
        resource_type: str,
        resource_id: int,
        user_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        移除可见性过滤器，将指定用户从资源的可见性白名单中移除。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"iam/visibility-filters/{jsonable_encoder(resource_type)}/{jsonable_encoder(resource_id)}/{jsonable_encoder(user_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawIamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_api_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse]:
        """
        List API key metadata for the authenticated user. Raw keys and hashes are never returned.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "iam/api-keys",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayInternalIamInternalWebApiKeyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_api_key(
        self, *, request: PostIamApiKeysRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse]:
        """
        Create an API key for the authenticated user. The raw API key is returned only once in this response.

        Parameters
        ----------
        request : PostIamApiKeysRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "iam/api-keys",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostIamApiKeysRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultInternalIamInternalWebCreateApiKeyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def revoke_api_key(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Revoke an API key owned by the authenticated user.

        Parameters
        ----------
        id : int
            API key ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"iam/api-keys/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_visibility_filters(
        self, *, resource_type: str, resource_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayUint]:
        """
        列出资源的可见性过滤器用户列表。返回被添加到可见性白名单中的用户 ID。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[GithubComMktAgiAixInternalPkgGinxResultArrayUint]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "iam/visibility-filters",
            method="GET",
            params={
                "resource_type": resource_type,
                "resource_id": resource_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    GithubComMktAgiAixInternalPkgGinxResultArrayUint,
                    parse_obj_as(
                        type_=GithubComMktAgiAixInternalPkgGinxResultArrayUint,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_visibility_filter(
        self, *, request: PostIamVisibilityFiltersRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        添加可见性过滤器，将指定用户添加到资源的可见性白名单中。

        Parameters
        ----------
        request : PostIamVisibilityFiltersRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "iam/visibility-filters",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=PostIamVisibilityFiltersRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_visibility_filter(
        self,
        resource_type: str,
        resource_id: int,
        user_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        移除可见性过滤器，将指定用户从资源的可见性白名单中移除。

        Parameters
        ----------
        resource_type : str
            Resource type

        resource_id : int
            Resource ID

        user_id : int
            User ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"iam/visibility-filters/{jsonable_encoder(resource_type)}/{jsonable_encoder(resource_id)}/{jsonable_encoder(user_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        GithubComMktAgiAixInternalPkgGinxCodeResp,
                        parse_obj_as(
                            type_=GithubComMktAgiAixInternalPkgGinxCodeResp,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
