# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_wisdom_internal_web_log_response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebLogResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_array_internal_wisdom_internal_web_purchase_item_response import (
    GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebPurchaseItemResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_graph_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebGraphResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_relation_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebRelationResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_trigger_status_vo import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebTriggerStatusVo,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_wisdom_delete_vo import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_wisdom_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse,
)
from ..types.github_com_mkt_agi_aix_internal_pkg_ginx_result_internal_wisdom_internal_web_wisdom_with_context_response import (
    GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomWithContextResponse,
)
from .raw_client import AsyncRawWisdomClient, RawWisdomClient
from .types.patch_wisdom_id_request_body import PatchWisdomIdRequestBody
from .types.post_wisdom_id_relations_request_body import PostWisdomIdRelationsRequestBody
from .types.post_wisdom_request import PostWisdomRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WisdomClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWisdomClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWisdomClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWisdomClient
        """
        return self._raw_client

    def list_contents(
        self,
        *,
        kind: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        community_id: typing.Optional[int] = None,
        min_confidence: typing.Optional[float] = None,
        promise_search: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        List content nodes with optional filters (kind, type, community_id, etc.)

        Parameters
        ----------
        kind : typing.Optional[str]
            kind filter

        type : typing.Optional[str]
            type filter

        community_id : typing.Optional[int]
            community ID filter

        min_confidence : typing.Optional[float]
            minimum confidence filter

        promise_search : typing.Optional[str]
            search by promise keyword

        offset : typing.Optional[int]
            pagination offset, default 0

        limit : typing.Optional[int]
            pagination limit, default 20, max 100

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.list_contents()
        """
        _response = self._raw_client.list_contents(
            kind=kind,
            type=type,
            community_id=community_id,
            min_confidence=min_confidence,
            promise_search=promise_search,
            offset=offset,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def create_content(
        self, *, request: PostWisdomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse:
        """
        Create a new content node in the property graph

        Parameters
        ----------
        request : PostWisdomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.create_content(
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create_content(request=request, request_options=request_options)
        return _response.data

    def get_content(
        self, id: int, *, depth: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomWithContextResponse:
        """
        Get a content node by ID with optional depth context (0 or 1)

        Parameters
        ----------
        id : int
            Content ID

        depth : typing.Optional[int]
            Context depth: 0 (default) or 1

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomWithContextResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.get_content(
            id=1,
        )
        """
        _response = self._raw_client.get_content(id, depth=depth, request_options=request_options)
        return _response.data

    def delete_content(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo:
        """
        Delete a content node by ID

        Parameters
        ----------
        id : int
            Content ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.delete_content(
            id=1,
        )
        """
        _response = self._raw_client.delete_content(id, request_options=request_options)
        return _response.data

    def update_content(
        self, id: int, *, request: PatchWisdomIdRequestBody, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse:
        """
        Update a content node's fields with optimistic locking via version

        Parameters
        ----------
        id : int
            Content ID

        request : PatchWisdomIdRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.update_content(
            id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.update_content(id, request=request, request_options=request_options)
        return _response.data

    def get_content_logs(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebLogResponse:
        """
        Get audit log entries for a specific content node

        Parameters
        ----------
        id : int
            Content ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebLogResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.get_content_logs(
            id=1,
        )
        """
        _response = self._raw_client.get_content_logs(id, request_options=request_options)
        return _response.data

    def add_relation(
        self,
        id: int,
        *,
        request: PostWisdomIdRelationsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebRelationResponse:
        """
        Add a directed relation edge from source content to target content

        Parameters
        ----------
        id : int
            Source content ID

        request : PostWisdomIdRelationsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebRelationResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.add_relation(
            id=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.add_relation(id, request=request, request_options=request_options)
        return _response.data

    def remove_relation(
        self, id: int, rid: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo:
        """
        Remove a relation edge by relation ID

        Parameters
        ----------
        id : int
            Source content ID

        rid : int
            Relation ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.remove_relation(
            id=1,
            rid=1,
        )
        """
        _response = self._raw_client.remove_relation(id, rid, request_options=request_options)
        return _response.data

    def cluster_contents(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebTriggerStatusVo:
        """
        Trigger community detection clustering on user's content graph

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebTriggerStatusVo
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.cluster_contents()
        """
        _response = self._raw_client.cluster_contents(request_options=request_options)
        return _response.data

    def list_purchased_communities(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebPurchaseItemResponse:
        """
        List the current user's purchased community access grants

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebPurchaseItemResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.list_purchased_communities()
        """
        _response = self._raw_client.list_purchased_communities(request_options=request_options)
        return _response.data

    def get_subgraph(
        self, *, community_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebGraphResponse:
        """
        Get the content subgraph for a specific community

        Parameters
        ----------
        community_id : int
            Community ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebGraphResponse
            OK

        Examples
        --------
        from MKT_AGI import MktAgiApi

        client = MktAgiApi(
            api_key="YOUR_API_KEY",
        )
        client.wisdom.get_subgraph(
            community_id=1,
        )
        """
        _response = self._raw_client.get_subgraph(community_id=community_id, request_options=request_options)
        return _response.data


class AsyncWisdomClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWisdomClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWisdomClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWisdomClient
        """
        return self._raw_client

    async def list_contents(
        self,
        *,
        kind: typing.Optional[str] = None,
        type: typing.Optional[str] = None,
        community_id: typing.Optional[int] = None,
        min_confidence: typing.Optional[float] = None,
        promise_search: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        List content nodes with optional filters (kind, type, community_id, etc.)

        Parameters
        ----------
        kind : typing.Optional[str]
            kind filter

        type : typing.Optional[str]
            type filter

        community_id : typing.Optional[int]
            community ID filter

        min_confidence : typing.Optional[float]
            minimum confidence filter

        promise_search : typing.Optional[str]
            search by promise keyword

        offset : typing.Optional[int]
            pagination offset, default 0

        limit : typing.Optional[int]
            pagination limit, default 20, max 100

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.list_contents()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_contents(
            kind=kind,
            type=type,
            community_id=community_id,
            min_confidence=min_confidence,
            promise_search=promise_search,
            offset=offset,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def create_content(
        self, *, request: PostWisdomRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse:
        """
        Create a new content node in the property graph

        Parameters
        ----------
        request : PostWisdomRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.create_content(
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_content(request=request, request_options=request_options)
        return _response.data

    async def get_content(
        self, id: int, *, depth: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomWithContextResponse:
        """
        Get a content node by ID with optional depth context (0 or 1)

        Parameters
        ----------
        id : int
            Content ID

        depth : typing.Optional[int]
            Context depth: 0 (default) or 1

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomWithContextResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.get_content(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_content(id, depth=depth, request_options=request_options)
        return _response.data

    async def delete_content(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo:
        """
        Delete a content node by ID

        Parameters
        ----------
        id : int
            Content ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.delete_content(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_content(id, request_options=request_options)
        return _response.data

    async def update_content(
        self, id: int, *, request: PatchWisdomIdRequestBody, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse:
        """
        Update a content node's fields with optimistic locking via version

        Parameters
        ----------
        id : int
            Content ID

        request : PatchWisdomIdRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.update_content(
                id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_content(id, request=request, request_options=request_options)
        return _response.data

    async def get_content_logs(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebLogResponse:
        """
        Get audit log entries for a specific content node

        Parameters
        ----------
        id : int
            Content ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebLogResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.get_content_logs(
                id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_content_logs(id, request_options=request_options)
        return _response.data

    async def add_relation(
        self,
        id: int,
        *,
        request: PostWisdomIdRelationsRequestBody,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebRelationResponse:
        """
        Add a directed relation edge from source content to target content

        Parameters
        ----------
        id : int
            Source content ID

        request : PostWisdomIdRelationsRequestBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebRelationResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.add_relation(
                id=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_relation(id, request=request, request_options=request_options)
        return _response.data

    async def remove_relation(
        self, id: int, rid: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo:
        """
        Remove a relation edge by relation ID

        Parameters
        ----------
        id : int
            Source content ID

        rid : int
            Relation ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebWisdomDeleteVo
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.remove_relation(
                id=1,
                rid=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_relation(id, rid, request_options=request_options)
        return _response.data

    async def cluster_contents(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebTriggerStatusVo:
        """
        Trigger community detection clustering on user's content graph

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebTriggerStatusVo
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.cluster_contents()


        asyncio.run(main())
        """
        _response = await self._raw_client.cluster_contents(request_options=request_options)
        return _response.data

    async def list_purchased_communities(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebPurchaseItemResponse:
        """
        List the current user's purchased community access grants

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultArrayInternalWisdomInternalWebPurchaseItemResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.list_purchased_communities()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_purchased_communities(request_options=request_options)
        return _response.data

    async def get_subgraph(
        self, *, community_id: int, request_options: typing.Optional[RequestOptions] = None
    ) -> GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebGraphResponse:
        """
        Get the content subgraph for a specific community

        Parameters
        ----------
        community_id : int
            Community ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GithubComMktAgiAixInternalPkgGinxResultInternalWisdomInternalWebGraphResponse
            OK

        Examples
        --------
        import asyncio

        from MKT_AGI import AsyncMktAgiApi

        client = AsyncMktAgiApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.wisdom.get_subgraph(
                community_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subgraph(community_id=community_id, request_options=request_options)
        return _response.data
