# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_accounts_internal_web_avatar_upload_url_req import InternalAccountsInternalWebAvatarUploadUrlReq

PostUserMeAvatarUploadUrlRequest = typing.Union[
    typing.Dict[str, typing.Any], InternalAccountsInternalWebAvatarUploadUrlReq
]
