# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.internal_bulletin_internal_web_update_bulletin_req import InternalBulletinInternalWebUpdateBulletinReq

PutAdminBulletinsIdRequestBody = typing.Union[
    typing.Dict[str, typing.Any], InternalBulletinInternalWebUpdateBulletinReq
]
